VerdanturfTown_ContestHall_MapScripts:: @ 8153E95
	.byte 0

VerdanturfTown_ContestHall_EventScript_153E97:: @ 8153E97
	msgbox VerdanturfTown_ContestHall_Text_177FB4, 2
	end

VerdanturfTown_ContestHall_EventScript_153EA0:: @ 8153EA0
	msgbox VerdanturfTown_ContestHall_Text_178091, 2
	end

VerdanturfTown_ContestHall_EventScript_153EA9:: @ 8153EA9
	msgbox VerdanturfTown_ContestHall_Text_178120, 2
	end

VerdanturfTown_ContestHall_EventScript_153EB2:: @ 8153EB2
	msgbox VerdanturfTown_ContestHall_Text_1781A5, 3
	end

VerdanturfTown_ContestHall_Text_177FB4:: @ 8177FB4
	.string "Which Contest are you entering?\n"
	.string "Want a piece of advice?\p"
	.string "In any Contest, for example, a Cute\n"
	.string "Contest, I don't think they judge you\l"
	.string "only on cuteness in the first round.\p"
	.string "You need to work out ways for raising\n"
	.string "Pokémon better.$"

VerdanturfTown_ContestHall_Text_178091:: @ 8178091
	.string "I raised my Pokémon to be cute.\p"
	.string "I found out you can put Pokémon in\n"
	.string "a Contest for cuteness!\p"
	.string "I'm so glad I raised my Pokémon with\n"
	.string "loving care…$"

VerdanturfTown_ContestHall_Text_178120:: @ 8178120
	.string "My Pokémon rules!\p"
	.string "It's cool, tough yet beautiful, cute,\n"
	.string "and smart. It's complete!\p"
	.string "I may as well go for wins in every\n"
	.string "single Contest.$"

VerdanturfTown_ContestHall_Text_1781A5:: @ 81781A5
	.string "Pokémon Contests\n"
	.string "Normal Rank Stage!$"
