MatchCall_Text_Mom1:: @ 82B227B
	.string "MOM: Your father and you…\n"
	.string "Everyone is captivated by POKéMON.\p"
	.string "What is the charm of POKéMON?\p"
	.string "Me?\n"
	.string "I adore POKéMON that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom2:: @ 82B2310
	.string "MOM: Hi, {PLAYER}!\n"
	.string "Your father keeps himself locked\l"
	.string "away in the PETALBURG GYM.\p"
	.string "He comes home every so often.\n"
	.string "But he goes back to the GYM when\l"
	.string "he's eaten everything he can.\p"
	.string "I'm guessing that losing to you\n"
	.string "was a big blow to his pride!$"

MatchCall_Text_Mom3:: @ 82B23F3
	.string "MOM: {PLAYER}…\n"
	.string "Don't worry about me or the house.\p"
	.string "Wear those RUNNING SHOES until\n"
	.string "they fall apart, honey!$"

MatchCall_Text_Roxanne1:: @ 82B2456
	.string "ROXANNE: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2:: @ 82B250E
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3:: @ 82B25C1
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4:: @ 82B2607
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1:: @ 82B2659
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2:: @ 82B275D
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3:: @ 82B286F
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My GYM's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4:: @ 82B28D1
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1:: @ 82B2912
	.string "WATTSON: Oh, it's you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2:: @ 82B29CA
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3:: @ 82B2AB6
	.string "WATTSON: Oh, it's you!\n"
	.string "My GYM's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4:: @ 82B2B01
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1:: @ 82B2B4D
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2:: @ 82B2C0E
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the GYM's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3:: @ 82B2CF1
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "Our GYM's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4:: @ 82B2D54
	.string "FLANNERY: {PLAYER}…\n"
	.string "I'm positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1:: @ 82B2DA4
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the GYM, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2:: @ 82B2E2B
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Winona3:: @ 82B2EC2
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4:: @ 82B2F16
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1:: @ 82B2F97
	.string "TATE: Oh! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our GYM!\p"
	.string "TATE: When our GYM is ready…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2:: @ 82B306E
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3:: @ 82B3158
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our GYM is ready!\n"
	.string "LIZA: Our GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4:: @ 82B31CD
	.string "TATE: {PLAYER}, the battle we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all battle again!$"

MatchCall_Text_Juan1:: @ 82B3249
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our battle together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2:: @ 82B32EC
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3:: @ 82B33AA
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS GYM has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4:: @ 82B341E
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney:: @ 82B34CC
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to battle with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the POKéMON LEAGUE.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Phoebe:: @ 82B3561
	.string "PHOEBE: Hi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia:: @ 82B35E4
	.string "GLACIA: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the POKéMON LEAGUE…$"

MatchCall_Text_Drake:: @ 82B368B
	.string "DRAKE: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the BATTLE\l"
	.string "FRONTIER that tests the skills of\l"
	.string "TRAINERS.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the POKéMON LEAGUE!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Wallace:: @ 82B3790
	.string "WALLACE: Hello, {PLAYER}{KUN}.\n"
	.string "Have you met STEVEN?\p"
	.string "He is…\n"
	.string "Actually incredibly skilled.\p"
	.string "However, he's an odd soul who\n"
	.string "rarely battles.\p"
	.string "Instead, he would rather look for\n"
	.string "rare stones.\p"
	.string "I'm sure he's digging in a cave or\n"
	.string "a craggy mountain somewhere.\p"
	.string "But what is a rare stone exactly?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall: @ 82B38C1
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green POKéMON\n"
	.string "flying high in the sky.\p"
	.string "I…\n"
	.string "I've never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this maybe a major discovery?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall: @ 82B39C6
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "BRENDAN: Hey, {PLAYER}!\n"
	.string "I was in PACIFIDLOG just now.\p"
	.string "I saw this huge green POKéMON\n"
	.string "flying across the sky.\p"
	.string "I've never seen anything that\n"
	.string "amazing before.\p"
	.string "I wish you could've seen it,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1:: @ 2B3AB3
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "He must love the sea still.$"

MatchCall_Text_May2:: @ 2B3B3F
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "You know how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS?\p"
	.string "For some reason, the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_May3:: @ 2B3C13
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Do you remember a man named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, remember?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_May4:: @ 2B3CF3
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "joins RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5:: @ 2B3D4B
	.string "MAY: {PLAYER}{KUN}, how are you?\p"
	.string "I'm out on ROUTE 111 now.\p"
	.string "I'm going to get a rest at an old\n"
	.string "lady's house.\p"
	.string "She lives just north of\n"
	.string "the desert.$"

MatchCall_Text_May6:: @ 2B3DD1
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it seems\n"
	.string "to mysteriously come and go.\p"
	.string "I wish I could see it.$"

MatchCall_Text_May7:: @ 2B3E69
	.string "MAY: {PLAYER}{KUN}, yahoo!\n"
	.string "I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it often rains.\p"
	.string "I got soaked!$"

MatchCall_Text_May8:: @ 2B3ECD
	.string "MAY: {PLAYER}{KUN}, hi.\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "Maybe as a result, it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_May9:: @ 2B3F2B
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But on the way, around JAGGED\n"
	.string "PASS, I ran into some bad-looking\l"
	.string "characters. The mood was ugly!$"

MatchCall_Text_May10:: @ 2B3FFB
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_May11:: @ 2B402B
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Don't you think it's neat?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "Did you know there's more?\p"
	.string "There's a POKéMON move that lets\n"
	.string "you go to the bottom of the sea.$"

MatchCall_Text_May12:: @ 2B414B
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Hope things are okay!\p"
	.string "Have you been on the sea and\n"
	.string "found your way to the other side\l"
	.string "blocked?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Easy!$"

MatchCall_Text_May13:: @ 2B4228
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "How's it going?\n"
	.string "Are you filling your POKéDEX?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And there are three of them!\p"
	.string "I would love to see even one…$"

MatchCall_Text_May14:: @ 2B42E0
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER?\p"
	.string "That means you don't have far\n"
	.string "to go, do you?$"

MatchCall_Text_May15:: @ 2B4350
	.string "MAY: There isn't a single TRAINER\n"
	.string "left in HOENN who doesn't know who\l"
	.string "you are, {PLAYER}{KUN}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}{KUN}, they're all\l"
	.string "surprised!$"

MatchCall_Text_Brendan1:: @ 2B43EF
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "I guess he must love\n"
	.string "the sea still.$"

MatchCall_Text_Brendan2:: @ 2B4486
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "I don't get how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS.\p"
	.string "I mean, not when the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_Brendan3:: @ 2B4560
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Do you remember a guy named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, right?\p"
	.string "Well, it turns out his little\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_Brendan4:: @ 2B463F
	.string "BRENDAN: This voice… {PLAYER}?\p"
	.string "They gave RUSTURF TUNNEL its name\n"
	.string "because it joins RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you know that?$"

MatchCall_Text_Brendan5:: @ 2B46B7
	.string "BRENDAN: {PLAYER}, what's up?\p"
	.string "Hey, I'm out on ROUTE 111 now.\p"
	.string "I'm going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6:: @ 2B4761
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it can be\n"
	.string "seen only sometimes.\p"
	.string "I'd like to see that!$"

MatchCall_Text_Brendan7:: @ 2B47F4
	.string "BRENDAN: Who's this? Oh, {PLAYER}?\n"
	.string "Guess what? I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it rains all the time.\p"
	.string "I got soaked to the bone!$"

MatchCall_Text_Brendan8:: @ 2B4882
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "That's probably why it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_Brendan9:: @ 2B4909
	.string "BRENDAN: Hey there, {PLAYER}.\p"
	.string "I was on my way back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But around JAGGED PASS, I ran into\n"
	.string "some nasty-looking characters.\p"
	.string "Those creeps…\n"
	.string "I think they were TEAM MAGMA.$"

MatchCall_Text_Brendan10:: @ 2B49C4
	.string "BRENDAN: Hi, {PLAYER}!\n"
	.string "Did you catch the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_Brendan11:: @ 2B4A44
	.string "BRENDAN: Hey there, {PLAYER}!\n"
	.string "Don't you think it's awesome?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "And, there's a move that lets you\n"
	.string "travel to the bottom of the sea.\p"
	.string "Man, POKéMON can do anything!$"

MatchCall_Text_Brendan12:: @ 2B4B28
	.string "BRENDAN: Howdy, {PLAYER}!\n"
	.string "How are you holding up?\p"
	.string "Ever found your way to the other\n"
	.string "side blocked while on the sea?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches at the bottom.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Simple!$"

MatchCall_Text_Brendan13:: @ 2B4C15
	.string "BRENDAN: Hey there, {PLAYER}!\p"
	.string "How's it going? Filling up your\n"
	.string "POKéDEX successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And not just one--three!\p"
	.string "I'd love to catch even one…$"

MatchCall_Text_Brendan14:: @ 2B4CD8
	.string "BRENDAN: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER? Awesome!\p"
	.string "You're getting awful close now!$"

MatchCall_Text_Brendan15:: @ 2B4D46
	.string "BRENDAN: There isn't a TRAINER in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}, they get pretty\l"
	.string "envious!$"

MatchCall_Text_Wally1:: @ 2B4DE2
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a TRAINER like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2:: @ 2B4E57
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3:: @ 2B4EA5
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4:: @ 2B4F41
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is amazing!\p"
	.string "When I have my POKéMON with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through POKéMON!$"

MatchCall_Text_Wally5:: @ 2B4FF3
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I'm talented…\p"
	.string "Oh, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, it's the POKéMON that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6:: @ 2B50B1
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Wally7:: @ 2B5100
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I'm on an adventure with\n"
	.string "my very own POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1:: @ 2B5184
	.string "SCOTT: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how POKéMON can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like POKéMON, you can find\n"
	.string "TRAINERS everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2:: @ 2B5275
	.string "SCOTT: I'm on ROUTE 119 right now.\n"
	.string "It's teeming with TRAINERS!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3:: @ 2B5323
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE?\p"
	.string "The place is a memorial to POKéMON\n"
	.string "that have passed away.\p"
	.string "It's somewhere every TRAINER\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4:: @ 2B53DB
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5:: @ 2B54A5
	.string "SCOTT: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough TRAINERS\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "And I don't raise POKéMON…$"

MatchCall_Text_Scott6:: @ 2B5541
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the POKéMON LEAGUE when you've\l"
	.string "collected all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the POKéMON LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7:: @ 2B56CA
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Norman1:: @ 82B5719
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2:: @ 82B5795
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3:: @ 82B584D
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4:: @ 82B58E3
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5:: @ 82B5979
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6:: @ 82B5A07
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7:: @ 82B5A69
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8:: @ 82B5ACF
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9:: @ 82B5B5E
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1:: @ 82B5B95
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "Have you been to MAUVILLE\n"
	.string "already?\p"
	.string "You should visit the BIKE SHOP\n"
	.string "and get a MACH BIKE.\p"
	.string "Then, try exploring the GRANITE\n"
	.string "CAVE thoroughly.\p"
	.string "You may make a new discovery\n"
	.string "there.$"

MatchCall_Text_Steven2:: @ 82B5C53
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "I've met a lot of different\n"
	.string "TRAINERS so far.\p"
	.string "But you're one of a kind.\n"
	.string "You're not like anyone else.$"

MatchCall_Text_Steven3:: @ 82B5CC9
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "When you're on an adventure with\n"
	.string "your POKéMON, what do you think?\p"
	.string "Do you consider them to be strong\n"
	.string "partners?\p"
	.string "Do you think of them as fun\n"
	.string "companions?\p"
	.string "Depending on how you think, your\n"
	.string "adventure's significance changes.$"

MatchCall_Text_Steven4:: @ 82B5DB4
	.string "STEVEN: Hello?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "I'm involved in a spot of trouble\n"
	.string "at the SPACE CENTER.\p"
	.string "I'm sorry, but I can't talk now.\n"
	.string "Bye!$"

MatchCall_Text_Steven5:: @ 82B5E26
	.string "STEVEN: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "There's no need to talk.\n"
	.string "It's past time for talking.\p"
	.string "You have to believe in yourself\n"
	.string "and do what's right.$"

MatchCall_Text_Steven6:: @ 82B5EA2
	.string "… … … … … …\p"
	.string "STEVEN appears not to be getting\n"
	.string "the call…$"

MatchCall_Text_Steven7:: @ 82B5ED9
	.string "STEVEN: {PLAYER}{KUN}… Congratulations\n"
	.string "for entering the HALL OF FAME.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I hope we can meet again\n"
	.string "somewhere!$"

MatchCall_Text_BirchRegisterCall: @ 82B5F52
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}!\n"
	.string "I've already heard about you!\p"
	.string "It seems your POKéNAV's been\n"
	.string "upgraded with MATCH CALL.\p"
	.string "Well, I should register, too!\p"
	.string "That way, I'd be able to examine\n"
	.string "your POKéDEX even while you're\l"
	.string "out in the field.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch: @ 82B603A
	.string "{COLOR DARK_GREY}Registered PROF. BIRCH\n"
	.string "in the POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When one has both\n"
	.string "the POKéDEX and POKéNAV, studying\l"
	.string "POKéMON becomes more fun, eh?$"

MatchCall_Text_MrStone1:: @ 82B60C0
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "Since you called me, the POKéNAV\n"
	.string "must be working properly!\p"
	.string "Other people will be registered,\n"
	.string "so try calling them up, too!\p"
	.string "Good! Good!\n"
	.string "You seem to be quite happy!\p"
	.string "Hm…\n"
	.string "How could I know that?\p"
	.string "It's because I'm looking down at\n"
	.string "you from my office window!\p"
	.string "Wahahaha!\n"
	.string "See you again!$"

MatchCall_Text_MrStone2:: @ 82B61E6
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "What's wrong? Have you forgotten\n"
	.string "about that little errand of mine?\p"
	.string "I need you to deliver my letter\n"
	.string "to STEVEN in DEWFORD.\p"
	.string "After that, deliver our parcel to\n"
	.string "CAPT. STERN in SLATEPORT.\p"
	.string "You remember, don't you?\p"
	.string "Now, since I am a busy PRESIDENT,\n"
	.string "I have to go! Bye-bye!$"

MatchCall_Text_MrStone3:: @ 82B6302
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Ah, so you've met STEVEN!\n"
	.string "I'd better reward you, then!\p"
	.string "When you visit RUSTBORO again,\n"
	.string "come see me at my office.\p"
	.string "I'll be waiting for you!$"

MatchCall_Text_MrStone4:: @ 82B63A0
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Did you know that DEVON was\n"
	.string "digging the RUSTURF TUNNEL?\p"
	.string "But we shut down the operation to\n"
	.string "protect the POKéMON in the area.\p"
	.string "It's a no-brainer, really.\p"
	.string "It's more important to let POKéMON\n"
	.string "live in peace than worry about our\l"
	.string "own convenience.$"

MatchCall_Text_MrStone5:: @ 82B64A2
	.string "MR. STONE: Hello, hello, {PLAYER}{KUN}!\p"
	.string "I heard from someone in PETALBURG\n"
	.string "that you're NORMAN's child!\p"
	.string "No wonder you're such a capable\n"
	.string "being!$"

MatchCall_Text_MrStone6:: @ 82B6526
	.string "MR. STONE: What's that?\p"
	.string "You battled your own father and\n"
	.string "defeated him?\p"
	.string "That's astounding!\p"
	.string "I had no idea that I befriended\n"
	.string "someone so special! Wahaha!$"

MatchCall_Text_MrStone7:: @ 82B65BB
	.string "Hello!\n"
	.string "This is DEVON CORPORATI…\l"
	.string "Oh, hello, {PLAYER}!\p"
	.string "Our PRESIDENT was here a little\n"
	.string "while ago, but he's gone out.\p"
	.string "Our PRESIDENT is busy, but you\n"
	.string "seem to be just as busy, {PLAYER}.$"

MatchCall_Text_MrStone8:: @ 82B6664
	.string "…Huh? …What's that?\p"
	.string "GROU… Yes? …DON?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9:: @ 82B66B1
	.string "…Huh? …What's that?\p"
	.string "Seaflo… Yes? …Caver…?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10:: @ 82B6703
	.string "MR. STONE: {PLAYER}{KUN}! It's me!\p"
	.string "You were apparently involved in all\n"
	.string "sorts of things, but I, being busy,\l"
	.string "haven't a clue exactly what!\p"
	.string "However, I urge you to take\n"
	.string "the road you believe in and walk it.\p"
	.string "I'll always be in your corner!\n"
	.string "Take care!$"

MatchCall_Text_MrStone11:: @ 82B67ED
	.string "MR. STONE: … … … … … …\n"
	.string "Is this maybe {PLAYER}{KUN}?\p"
	.string "Your voice is so full of confidence,\n"
	.string "I didn't recognize you right off!\p"
	.string "Hm! You must come visit us at DEVON\n"
	.string "sometime!$"
