FallarborTown_ContestHall_MapScripts:: @ 8153ACE
	.byte 0

FallarborTown_ContestHall_EventScript_153ACF:: @ 8153ACF
	msgbox FallarborTown_ContestHall_Text_177335, 2
	end

FallarborTown_ContestHall_EventScript_153AD8:: @ 8153AD8
	msgbox FallarborTown_ContestHall_Text_1773C6, 2
	end

FallarborTown_ContestHall_EventScript_153AE1:: @ 8153AE1
	msgbox FallarborTown_ContestHall_Text_177437, 2
	end

FallarborTown_ContestHall_EventScript_153AEA:: @ 8153AEA
	msgbox FallarborTown_ContestHall_Text_1774B1, 3
	end

FallarborTown_ContestHall_Text_177335:: @ 8177335
	.string "We do all right in the preliminary round,\n"
	.string "but we can never win the appeals…\p"
	.string "Maybe it means I have to watch what\n"
	.string "other contestants are doing…$"

FallarborTown_ContestHall_Text_1773C6:: @ 81773C6
	.string "See!\n"
	.string "My POKéMON won all these RIBBONS!\p"
	.string "Have your POKéMON earned any RIBBONS?\n"
	.string "You can check them on your POKéNAV.$"

FallarborTown_ContestHall_Text_177437:: @ 8177437
	.string "I can't beat GYM LEADERS…\p"
	.string "I can't win any CONTESTS…\p"
	.string "I've been here, there, and everywhere,\n"
	.string "and it's all for naught…$"

FallarborTown_ContestHall_Text_1774B1:: @ 81774B1
	.string "POKéMON CONTESTS\n"
	.string "SUPER RANK STAGE!$"
