CeruleanCityHouse3_MapScripts::
	.byte 0

CeruleanHouse3_NPC1::
    msgbox CeruleanHouse3_NPC_1, MSGBOX_NPC
	release
	end

CeruleanHouse3_NPC2::
    msgbox CeruleanHouse3_NPC_2, MSGBOX_NPC
	release
	end

CeruleanHouse3_NPC_1::
    .string "Wahahaha!\p"
	.string "Those Team Rocket got what they\n"
	.string "deserved!\p"
	.string "After they wrecked my house they\n"
	.string "got defeated by some kid!\l"
	.string "Wahahaha!$"

CeruleanHouse3_NPC_2::
    .string "Cleaning up the mess Team Rocket\n"
	.string "created is hard work.\p"
	.string "I think I can finish it soon!$"
