OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 81FBE86
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
	.string "When a POKéMON battle starts, the\n"
	.string "one at the left of the list goes\l"
	.string "out first.\p"
	.string "So, when you get more POKéMON in\n"
	.string "your party, try switching around\l"
	.string "the order of your POKéMON.\p"
	.string "It could give you an advantage.$"

