CeruleanCityMart_MapScripts::
	.byte 0

CeruleanMart_NPC_1::
    msgbox CeruleanMart_NPC1, MSGBOX_NPC
	release
	end

CeruleanMart_NPC_2::
    msgbox CeruleanMart_NPC2, MSGBOX_NPC
	release
	end

CeruleanMart_NPC1::
    .string "Repel not only keeps bugs away,\n"
    .string "it also works on weak Pokémon.\p"
    .string "Put your strongest Pokémon at the\n"
    .string "left of the Pokémon List.\p"
    .string "If your first Pokémon is strong,\n"
    .string "Repel's effect is boosted.$"

CeruleanMart_NPC2::
    .string "Do you know about Rare Candy?\n"
    .string "They don't sell it in shops.\p"
    .string "I think it makes Pokémon grow\n"
    .string "very quickly all of a sudden.$"

