	.align 2
gTilesetTiles_Petalburg:: @ 8339E08
	.incbin "data/tilesets/secondary/petalburg/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Petalburg:: @ 833A704
	.incbin "data/tilesets/secondary/petalburg/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/15.gbapal"

	.align 2
gTilesetTiles_Rustboro:: @ 833A904
	.incbin "data/tilesets/secondary/rustboro/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Rustboro:: @ 833BEC0
	.incbin "data/tilesets/secondary/rustboro/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dewford:: @ 833C0C0
	.incbin "data/tilesets/secondary/dewford/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dewford:: @ 833D540
	.incbin "data/tilesets/secondary/dewford/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/15.gbapal"

	.align 2
gTilesetTiles_Slateport:: @ 833D740
	.incbin "data/tilesets/secondary/slateport/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Slateport:: @ 833F708
	.incbin "data/tilesets/secondary/slateport/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mauville:: @ 833F908
	.incbin "data/tilesets/secondary/mauville/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mauville:: @ 834172C
	.incbin "data/tilesets/secondary/mauville/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lavaridge:: @ 834192C
	.incbin "data/tilesets/secondary/lavaridge/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lavaridge:: @ 8342E28
	.incbin "data/tilesets/secondary/lavaridge/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fallarbor:: @ 8343028
	.incbin "data/tilesets/secondary/fallarbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fallarbor:: @ 83447A0
	.incbin "data/tilesets/secondary/fallarbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fortree:: @ 83449A0
	.incbin "data/tilesets/secondary/fortree/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fortree:: @ 8346020
	.incbin "data/tilesets/secondary/fortree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lilycove:: @ 8346220
	.incbin "data/tilesets/secondary/lilycove/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lilycove:: @ 83475C0
	.incbin "data/tilesets/secondary/lilycove/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mossdeep:: @ 83477C0
	.incbin "data/tilesets/secondary/mossdeep/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mossdeep:: @ 8348E10
	.incbin "data/tilesets/secondary/mossdeep/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/15.gbapal"

	.align 2
gTilesetTiles_EverGrande:: @ 8349010
	.incbin "data/tilesets/secondary/ever_grande/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EverGrande:: @ 8349C28
	.incbin "data/tilesets/secondary/ever_grande/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/15.gbapal"

	.align 2
gTilesetTiles_Pacifidlog:: @ 8349E28
	.incbin "data/tilesets/secondary/pacifidlog/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pacifidlog:: @ 834B5B4
	.incbin "data/tilesets/secondary/pacifidlog/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/15.gbapal"

	.align 2
gTilesetTiles_Sootopolis:: @ 834B7B4
	.incbin "data/tilesets/secondary/sootopolis/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Sootopolis:: @ 834C6B4
	.incbin "data/tilesets/secondary/sootopolis/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideWest:: @ 834C8B4
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideWest:: @ 834E3E4
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideEast:: @ 834E5E4
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideEast:: @ 834F984
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideBuilding:: @ 834FB84
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideBuilding:: @ 83508BC
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Shop:: @ 8350ABC
	.incbin "data/tilesets/secondary/shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Shop:: @ 83520DC
	.incbin "data/tilesets/secondary/shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonCenter:: @ 83522DC
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonCenter:: @ 8353574
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2
gTilesetTiles_Cave:: @ 8353774
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cave:: @ 8355260
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonSchool:: @ 8355460
	.incbin "data/tilesets/secondary/pokemon_school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonSchool:: @ 8355BA8
	.incbin "data/tilesets/secondary/pokemon_school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonFanClub:: @ 8355DA8
	.incbin "data/tilesets/secondary/pokemon_fan_club/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonFanClub:: @ 83566D4
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused1:: @ 83568D4
	.incbin "data/tilesets/secondary/unused_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused1:: @ 8356920
	.incbin "data/tilesets/secondary/unused_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_MeteorFalls:: @ 8356B20
	.incbin "data/tilesets/secondary/meteor_falls/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MeteorFalls:: @ 8358840
	.incbin "data/tilesets/secondary/meteor_falls/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/15.gbapal"

	.align 2
gTilesetTiles_OceanicMuseum:: @ 8358A40
	.incbin "data/tilesets/secondary/oceanic_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_OceanicMuseum:: @ 83599CC
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_CableClub:: @ 8359BCC
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/secondary/cable_club/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_CableClub:: @ 835EACC
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeashoreHouse:: @ 835ECCC
	.incbin "data/tilesets/secondary/seashore_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeashoreHouse:: @ 835F5A8
	.incbin "data/tilesets/secondary/seashore_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_PrettyPetalFlowerShop:: @ 835F7A8
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PrettyPetalFlowerShop:: @ 83603A0
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonDayCare:: @ 83605A0
	.incbin "data/tilesets/secondary/pokemon_day_care/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonDayCare:: @ 8360FDC
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/15.gbapal"

	.align 2
gTilesetTiles_Facility:: @ 83611DC
	.incbin "data/tilesets/secondary/facility/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Facility:: @ 8362E90
	.incbin "data/tilesets/secondary/facility/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/15.gbapal"

	.align 2
gTilesetTiles_BikeShop:: @ 8363090
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop:: @ 83643C0
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_RusturfTunnel:: @ 83645C0
	.incbin "data/tilesets/secondary/rusturf_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RusturfTunnel:: @ 8365008
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBrownCave:: @ 8365788
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseTree:: @ 8365EAC
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseShrub:: @ 8366614
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBlueCave:: @ 8366C30
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseYellowCave:: @ 8367368
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseRedCave:: @ 83679A0
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBaseBrownCave:: @ 8367BA0
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseTree:: @ 8368600
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseShrub:: @ 8369060
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseBlueCave:: @ 8369AC0
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseYellowCave:: @ 836A520
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseRedCave:: @ 836AF80
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2
gTilesetTiles_InsideOfTruck:: @ 836B9E0
	.incbin "data/tilesets/secondary/inside_of_truck/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideOfTruck:: @ 836BC3C
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/15.gbapal"

	.align 2
gTilesetTiles_Contest:: @ 836BE3C
	.incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Contest:: @ 836C990
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"

	.align 2
gTilesetTiles_LilycoveMuseum:: @ 836CB90
	.incbin "data/tilesets/secondary/lilycove_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LilycoveMuseum:: @ 836DEAC
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_BrendansMaysHouse:: @ 836E0AC
	.incbin "data/tilesets/secondary/brendans_mays_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BrendansMaysHouse:: @ 836F178
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lab:: @ 836F378
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lab:: @ 83703DC
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underwater:: @ 83705DC
	.incbin "data/tilesets/secondary/underwater/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underwater:: @ 8371798
	.incbin "data/tilesets/secondary/underwater/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding:: @ 8371998
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding:: @ 83733C4
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGameCorner:: @ 83735C4
	.incbin "data/tilesets/secondary/mauville_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGameCorner:: @ 8374288
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused2:: @ 8374488
	.incbin "data/tilesets/secondary/unused_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused2:: @ 83749B0
	.incbin "data/tilesets/secondary/unused_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_RustboroGym:: @ 8374BB0
	.incbin "data/tilesets/secondary/rustboro_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RustboroGym:: @ 8374F34
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_DewfordGym:: @ 8375134
	.incbin "data/tilesets/secondary/dewford_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DewfordGym:: @ 8375400
	.incbin "data/tilesets/secondary/dewford_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGym:: @ 8375600
	.incbin "data/tilesets/secondary/mauville_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGym:: @ 8375D84
	.incbin "data/tilesets/secondary/mauville_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavaridgeGym:: @ 8375F84
	.incbin "data/tilesets/secondary/lavaridge_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavaridgeGym:: @ 83762AC
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_PetalburgGym:: @ 83764AC
	.incbin "data/tilesets/secondary/petalburg_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PetalburgGym:: @ 8376B50
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_FortreeGym:: @ 8376D50
	.incbin "data/tilesets/secondary/fortree_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FortreeGym:: @ 83770C4
	.incbin "data/tilesets/secondary/fortree_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGym:: @ 83772C4
	.incbin "data/tilesets/secondary/mossdeep_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGym:: @ 8377730
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SootopolisGym:: @ 8377930
	.incbin "data/tilesets/secondary/sootopolis_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SootopolisGym:: @ 8378AC4
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrickHousePuzzle:: @ 8378CC4
	.incbin "data/tilesets/secondary/trick_house_puzzle/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrickHousePuzzle:: @ 8379A78
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideShip:: @ 8379C78
	.incbin "data/tilesets/secondary/inside_ship/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideShip:: @ 837A848
	.incbin "data/tilesets/secondary/inside_ship/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBase:: @ 837AA48
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_SecretBase:: @ 8382A48
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2
gTilesetTiles_EliteFour:: @ 8382C48
	.incbin "data/tilesets/secondary/elite_four/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EliteFour:: @ 8383CC4
	.incbin "data/tilesets/secondary/elite_four/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontier:: @ 8383EC4
	.incbin "data/tilesets/secondary/battle_frontier/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontier:: @ 8384BC8
	.incbin "data/tilesets/secondary/battle_frontier/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePalace:: @ 8384DC8
	.incbin "data/tilesets/secondary/battle_palace/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePalace:: @ 8385540
	.incbin "data/tilesets/secondary/battle_palace/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleDome:: @ 8385740
	.incbin "data/tilesets/secondary/battle_dome/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleDome:: @ 8386990
	.incbin "data/tilesets/secondary/battle_dome/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFactory:: @ 8386B90
	.incbin "data/tilesets/secondary/battle_factory/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFactory:: @ 8387D7C
	.incbin "data/tilesets/secondary/battle_factory/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePike:: @ 8387F7C
	.incbin "data/tilesets/secondary/battle_pike/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePike:: @ 8389250
	.incbin "data/tilesets/secondary/battle_pike/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleArena:: @ 8389450
	.incbin "data/tilesets/secondary/battle_arena/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleArena:: @ 8389F8C
	.incbin "data/tilesets/secondary/battle_arena/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePyramid:: @ 838A18C
	.incbin "data/tilesets/secondary/battle_pyramid/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePyramid:: @ 838B39C
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/15.gbapal"

	.align 2
gTilesetTiles_MirageTower:: @ 838B59C
	.incbin "data/tilesets/secondary/mirage_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MirageTower:: @ 838CFE4
	.incbin "data/tilesets/secondary/mirage_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGameCorner:: @ 838D1E4
	.incbin "data/tilesets/secondary/mossdeep_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGameCorner:: @ 838D604
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_IslandHarbor:: @ 838D804
	.incbin "data/tilesets/secondary/island_harbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IslandHarbor:: @ 838F1D4
	.incbin "data/tilesets/secondary/island_harbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerHill:: @ 838F3D4
	.incbin "data/tilesets/secondary/trainer_hill/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerHill:: @ 83904C4
	.incbin "data/tilesets/secondary/trainer_hill/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/15.gbapal"

	.align 2
gTilesetTiles_NavelRock:: @ 83906C4
	.incbin "data/tilesets/secondary/navel_rock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NavelRock:: @ 8392258
	.incbin "data/tilesets/secondary/navel_rock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierRankingHall:: @ 8392458
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierRankingHall:: @ 8392CAC
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleTent:: @ 8392EAC
	.incbin "data/tilesets/secondary/battle_tent/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleTent:: @ 8393910
	.incbin "data/tilesets/secondary/battle_tent/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/15.gbapal"

	.align 2
gTilesetTiles_MysteryEventsHouse:: @ 8393B10
	.incbin "data/tilesets/secondary/mystery_events_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MysteryEventsHouse:: @ 8395478
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/15.gbapal"

	.align 2
gTilesetPalettes_UnionRoom:: @ 8395678
	.incbin "data/tilesets/secondary/union_room/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnionRoom:: @ 8395878
	.incbin "data/tilesets/secondary/union_room/tiles.4bpp.lz"

gTilesetPalettes_gTileset_Kanto_General::
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/00.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/01.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/02.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/03.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/04.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/05.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/06.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/07.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/08.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/09.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/10.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/11.gbapal"
	.incbin "data/tilesets/primary/gtileset_kanto_general/palettes/12.gbapal"

	.align 2
gTilesetTiles_gTileset_Kanto_General::
	.incbin "data/tilesets/primary/gtileset_kanto_general/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pallet::
	.incbin "data/tilesets/secondary/pallet/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pallet/palettes/12.gbapal"

	.align 2
gTilesetTiles_Pallet::
	.incbin "data/tilesets/secondary/pallet/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Viridian::
	.incbin "data/tilesets/secondary/viridian/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridian/palettes/12.gbapal"

	.align 2
gTilesetTiles_Viridian::
	.incbin "data/tilesets/secondary/viridian/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pewter::
	.incbin "data/tilesets/secondary/pewter/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewter/palettes/12.gbapal"

	.align 2
gTilesetTiles_Pewter::
	.incbin "data/tilesets/secondary/pewter/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cerulean::
	.incbin "data/tilesets/secondary/cerulean/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cerulean/palettes/12.gbapal"

	.align 2
gTilesetTiles_Cerulean::
	.incbin "data/tilesets/secondary/cerulean/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lavender::
	.incbin "data/tilesets/secondary/lavender/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavender/palettes/12.gbapal"

	.align 2
gTilesetTiles_Lavender::
	.incbin "data/tilesets/secondary/lavender/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Vermilion::
	.incbin "data/tilesets/secondary/vermilion/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilion/palettes/12.gbapal"

	.align 2
gTilesetTiles_Vermilion::
	.incbin "data/tilesets/secondary/vermilion/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Celadon::
	.incbin "data/tilesets/secondary/celadon/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadon/palettes/12.gbapal"

	.align 2
gTilesetTiles_Celadon::
	.incbin "data/tilesets/secondary/celadon/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fuchsia::
	.incbin "data/tilesets/secondary/fuchsia/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsia/palettes/12.gbapal"

	.align 2
gTilesetTiles_Fuchsia::
	.incbin "data/tilesets/secondary/fuchsia/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cinnabar::
	.incbin "data/tilesets/secondary/cinnabar/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabar/palettes/12.gbapal"

	.align 2
gTilesetTiles_Cinnabar::
	.incbin "data/tilesets/secondary/cinnabar/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Indigo::
	.incbin "data/tilesets/secondary/indigo/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/indigo/palettes/12.gbapal"

	.align 2
gTilesetTiles_Indigo::
	.incbin "data/tilesets/secondary/indigo/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Saffron::
	.incbin "data/tilesets/secondary/saffron/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffron/palettes/12.gbapal"

	.align 2
gTilesetTiles_Saffron::
	.incbin "data/tilesets/secondary/saffron/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianForest::
	.incbin "data/tilesets/secondary/viridianforest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianForest::
	.incbin "data/tilesets/secondary/viridianforest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoIndoor::
	.incbin "data/tilesets/primary/kantoindoor/palettes/00.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/01.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/02.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/03.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/04.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/05.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/06.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/07.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/08.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/09.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/10.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/11.gbapal"
	.incbin "data/tilesets/primary/kantoindoor/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoIndoor::
	.incbin "data/tilesets/primary/kantoindoor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoGateHouse::
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantogatehouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoGateHouse::
	.incbin "data/tilesets/secondary/kantogatehouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoCave::
	.incbin "data/tilesets/secondary/kantocave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantocave/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoCave::
	.incbin "data/tilesets/secondary/kantocave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RockTunnel::
	.incbin "data/tilesets/secondary/rocktunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/12.gbapal"

	.align 2
gTilesetTiles_RockTunnel::
	.incbin "data/tilesets/secondary/rocktunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DiggletsCave::
	.incbin "data/tilesets/secondary/diggletscave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/diggletscave/palettes/12.gbapal"

	.align 2
gTilesetTiles_DiggletsCave::
	.incbin "data/tilesets/secondary/diggletscave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UndergroundPath::
	.incbin "data/tilesets/secondary/undergroundpath/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/undergroundpath/palettes/12.gbapal"

	.align 2
gTilesetTiles_UndergroundPath::
	.incbin "data/tilesets/secondary/undergroundpath/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoPlayerHouse::
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantoplayerhouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoPlayerHouse::
	.incbin "data/tilesets/secondary/kantoplayerhouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ProfOakLab::
	.incbin "data/tilesets/secondary/profoaklab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/profoaklab/palettes/12.gbapal"

	.align 2
gTilesetTiles_ProfOakLab::
	.incbin "data/tilesets/secondary/profoaklab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoViridianSchool::
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantoviridianschool/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoViridianSchool::
	.incbin "data/tilesets/secondary/kantoviridianschool/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianCityGym::
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianCityGym::
	.incbin "data/tilesets/secondary/viridiancitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCityMuseum::
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterCityMuseum::
	.incbin "data/tilesets/secondary/pewtercitymuseum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCityGym::
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterCityGym::
	.incbin "data/tilesets/secondary/pewtercitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCityBikeShop::
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCityBikeShop::
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCityGym::
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCityGym::
	.incbin "data/tilesets/secondary/ceruleancitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCityCrashedHouse::
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCityCrashedHouse::
	.incbin "data/tilesets/secondary/ceruleancitycrashedhouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FanclubDaycareLavenderHouse::
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_FanclubDaycareLavenderHouse::
	.incbin "data/tilesets/secondary/fanclubdaycarelavenderhouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonTower::
	.incbin "data/tilesets/secondary/pokemontower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/12.gbapal"

	.align 2
gTilesetTiles_PokemonTower::
	.incbin "data/tilesets/secondary/pokemontower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionCityGym::
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_VermilionCityGym::
	.incbin "data/tilesets/secondary/vermilioncitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SliphCo::
	.incbin "data/tilesets/secondary/sliphco/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sliphco/palettes/12.gbapal"

	.align 2
gTilesetTiles_SliphCo::
	.incbin "data/tilesets/secondary/sliphco/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonRestruant::
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadonrestruant/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonRestruant::
	.incbin "data/tilesets/secondary/celadonrestruant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonInn::
	.incbin "data/tilesets/secondary/celadoninn/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadoninn/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonInn::
	.incbin "data/tilesets/secondary/celadoninn/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonGameCorner::
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadongamecorner/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonGameCorner::
	.incbin "data/tilesets/secondary/celadongamecorner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonCityGym::
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonCityGym::
	.incbin "data/tilesets/secondary/celadoncitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoSafariIndoor::
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantosafariindoor/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoSafariIndoor::
	.incbin "data/tilesets/secondary/kantosafariindoor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaCityGym::
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_FuchsiaCityGym::
	.incbin "data/tilesets/secondary/fuchsiacitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CinnabarIslandGym::
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CinnabarIslandGym::
	.incbin "data/tilesets/secondary/cinnabarislandgym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/12.gbapal"

	.align 2
gTilesetTiles_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemonmansion/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoPokemonLeague::
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoPokemonLeague::
	.incbin "data/tilesets/secondary/kantopokemonleague/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoHallofFame::
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoHallofFame::
	.incbin "data/tilesets/secondary/kantohalloffame/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronCityGym::
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronCityGym::
	.incbin "data/tilesets/secondary/saffroncitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SliphCo2::
	.incbin "data/tilesets/secondary/sliphco2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sliphco2/palettes/12.gbapal"

	.align 2
gTilesetTiles_SliphCo2::
	.incbin "data/tilesets/secondary/sliphco2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoSafari::
	.incbin "data/tilesets/secondary/kantosafari/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantosafari/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoSafari::
	.incbin "data/tilesets/secondary/kantosafari/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoPowerPlant::
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoPowerPlant::
	.incbin "data/tilesets/secondary/kantopowerplant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCave::
	.incbin "data/tilesets/secondary/ceruleancave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCave::
	.incbin "data/tilesets/secondary/ceruleancave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoamislands/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/12.gbapal"

	.align 2
gTilesetTiles_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoamislands/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Rustboro2::
	.incbin "data/tilesets/secondary/rustboro2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro2/palettes/12.gbapal"

	.align 2
gTilesetTiles_Rustboro2::
	.incbin "data/tilesets/secondary/rustboro2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoTrainerTower::
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoTrainerTower::
	.incbin "data/tilesets/secondary/kantotrainertower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lavaridge2::
	.incbin "data/tilesets/secondary/lavaridge2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge2/palettes/12.gbapal"

	.align 2
gTilesetTiles_Lavaridge2::
	.incbin "data/tilesets/secondary/lavaridge2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SSAnne::
	.incbin "data/tilesets/secondary/ssanne/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ssanne/palettes/12.gbapal"

	.align 2
gTilesetTiles_SSAnne::
	.incbin "data/tilesets/secondary/ssanne/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BillsHouse::
	.incbin "data/tilesets/secondary/billshouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/billshouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_BillsHouse::
	.incbin "data/tilesets/secondary/billshouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MeteorCave::
	.incbin "data/tilesets/secondary/meteorcave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/meteorcave/palettes/12.gbapal"

	.align 2
gTilesetTiles_MeteorCave::
	.incbin "data/tilesets/secondary/meteorcave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MagmaHideout::
	.incbin "data/tilesets/secondary/magmahideout/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/magmahideout/palettes/12.gbapal"

	.align 2
gTilesetTiles_MagmaHideout::
	.incbin "data/tilesets/secondary/magmahideout/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_mauville2::
	.incbin "data/tilesets/secondary/mauville2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville2/palettes/12.gbapal"

	.align 2
gTilesetTiles_mauville2::
	.incbin "data/tilesets/secondary/mauville2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_aqua_hideout::
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/aqua_hideout/palettes/12.gbapal"

	.align 2
gTilesetTiles_aqua_hideout::
	.incbin "data/tilesets/secondary/aqua_hideout/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_devon_corp::
	.incbin "data/tilesets/secondary/devon_corp/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/devon_corp/palettes/12.gbapal"

	.align 2
gTilesetTiles_devon_corp::
	.incbin "data/tilesets/secondary/devon_corp/tiles.4bpp.lz"
